### ISSUE TITLE
VimCurrentWord highlight group does not take effect

### ISSUE THREAD

**Issue by hongyuanjia** [liuchengxu/space-vim-theme#1]
Thanks for this amazing-looking color scheme!

I am using space-vim with `space-vim-theme` color scheme enabled by default in the latest version.

I found that `CurrentWord` highlight group is somehow linked to `Search`, which makes it extremely to find the cursor as it uses reverse effect. See pic below:

![image](https://user-images.githubusercontent.com/20545387/52545679-3a022500-2df4-11e9-849f-6b6111b462bf.png)

However, space-vim-dark does not have this issue:

![image](https://user-images.githubusercontent.com/20545387/52545708-91a09080-2df4-11e9-9679-ff798cfd4d9b.png)

In `space_vim_theme.vim`, you define a new color group called `VimCurrentWord` which is not the one that [vim_current_word](https://github.com/dominikduda/vim_current_word) plugin uses. I believe this is where the issue comes from.

https://github.com/liuchengxu/space-vim-theme/blob/9c74b24ccd57738efcd64fb583a0fed648b0f506/colors/space_vim_theme.vim#L277

Any insights? Thanks!

**Comment by liuchengxu** [comment]
Thanks for the report. Please pull and try the latest version.

**Comment by hongyuanjia** [comment]
Unfortunately, it does not work on my side.

But if I put lines below in `UserConfig()`, the issue goes away...

```vim
  hi CurrentWord ctermfg=NONE ctermbg=60 guifg=NONE guibg=#544a65 guisp=NONE cterm=NONE,underline gui=NONE,underline
  hi CurrentWordTwins ctermfg=NONE ctermbg=60 guifg=NONE guibg=#544a65 guisp=NONE cterm=NONE gui=NONE
```

Any thoughts?

**Comment by liuchengxu** [comment]
Can you ensure you have pulled the latest version? In the latest commit:

```vim
:hi CurrentWord
CurrentWord    xxx cterm=underline ctermbg=60 gui=underline guibg=#544a65
```

To highlight manually is definitely doable. You can customize any colors after you load a colorscheme.

**Comment by hongyuanjia** [comment]
Yes, I am pretty sure I pulled the latest version. Those two lines are copied from `space_vim_theme.vim` on my local machine.

![image](https://user-images.githubusercontent.com/20545387/52547331-eeef0e80-2e01-11e9-96be-3f540e81f8d7.png)

`CurrentWord` is still linked to `Search` on my side.  I have no idea what is going on...

**Comment by liuchengxu** [comment]
What does `:verbose hi CurrentWord` say?

**Comment by hongyuanjia** [comment]
Did not know how to pipe the message into vim's register. Anyway, here is the message:

![image](https://user-images.githubusercontent.com/20545387/52548775-822c4200-2e0a-11e9-89c0-497f026716e3.png)

It points to line 42:

```vim
hi! link CursorColumn CursorLine
```

**Comment by liuchengxu** [comment]
That makes sense. The plugins vim_current_word overrides the colors from space-vim-theme. 

You can use `:redir` to capture the message of an ex command to register, refer to http://vim.wikia.com/wiki/Capture_ex_command_output for more details.

**Comment by liuchengxu** [comment]
I don't know why your vim_current_word still defines its group, but you have found the quickest solution  anyway. What's more, I use https://github.com/neoclide/coc-highlight now.

**Comment by hongyuanjia** [comment]
> That makes sense. The plugins vim_current_word overrides the colors from space-vim-theme.
> 
> You can use `:redir` to capture the message of an ex command to register, refer to http://vim.wikia.com/wiki/Capture_ex_command_output for more details.

Thanks for the nice trick!

> I don't know why your vim_current_word still defines its group, but you have found the quickest solution anyway. What's more, I use https://github.com/neoclide/coc-highlight now.

Never mind, since manual setting works as expected.

Thanks again for your space-vim distro and all related works!
