### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by glepnir** [liuchengxu/space-vim-theme#2]
## Feature

_**1.**_`space_vim_plugins_in_hi = 1`  startify底部变黑色了。。不应该设置251，
![321](https://user-images.githubusercontent.com/41671631/53137005-155c3900-35bc-11e9-9c0f-2021ce003d4c.png)
_**2.**_我单独设置了 vim-gitgutter，默认不是用的bg，有ctermbg就有点丑.
![12312](https://user-images.githubusercontent.com/41671631/53137525-0c6c6700-35be-11e9-8457-7e9c93279663.png)
_**3.**_ 像spacevim-vim-dark 有listchars的颜色。vim-go会重置tab与indentline无法共同使用，所以添加listchar的颜色更加明显。

**Comment by liuchengxu** [comment]
请不要在一个 issue 里面描述多个问题。

**Comment by glepnir** [comment]
@liuchengxu  sry  一些建议。如果你觉得可以采纳的话。不合理可以忽略

**Comment by liuchengxu** [comment]
你应该把每个问题都描述清楚，配置是什么，现在是什么情况，期望是什么，不然我没办法快速复现并理解你的问题。

**Comment by glepnir** [comment]
> 你应该把每个问题都描述清楚，配置是什么，现在是什么情况，期望是什么，不然我没办法快速复现并理解你的问题。

为我的阐述，抱歉，我已经fork进行了修改 现在工作良好，feature可能基于我的个人意愿 。
