### ISSUE TITLE
python 代码第一次输入tab或者空格的时候，会标记为红色；使用space-vim-dark不存在这样的问题；

### ISSUE THREAD

**Issue by kumustone** [liuchengxu/space-vim-theme#3]
![image](https://user-images.githubusercontent.com/37612354/54328572-673b3080-4649-11e9-9523-74b7469771aa.png)

**Comment by liuchengxu** [comment]
你应该是自己配置了高亮尾部多余空格之类的，跟 space_vim_theme 没关系， 参见 https://vim.fandom.com/wiki/Highlight_unwanted_spaces。

这个是 minimal vimrc, 你可以自己测试下。

```vim
set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/space-vim-theme'
call plug#end()

colorscheme space_vim_theme
```
