### ISSUE TITLE
colorscheme space_vim_theme

### ISSUE THREAD

**Issue by jiahao-jayden** [liuchengxu/space-vim-theme#4]
> when I  set `colorscheme space_vim_theme`  there was an error  in the diagram

![error.png](https://i.loli.net/2019/08/24/pWTitaNSnPz5h1X.png)

**Comment by liuchengxu** [comment]
It's not an issue of space-vim-theme, you should check your own config. Reopen if you can reproduce with a minimal vimrc.

**Comment by ovidius72** [comment]
I can see the same errors 
Tried with a lot of different coloschemes but this error happens only with this theme.

![neovim_vim_____config_nvim_init__-_NVIM](https://user-images.githubusercontent.com/3592928/65080239-1c57f800-d9a1-11e9-85fb-59215c19aef5.jpg)

**Comment by liuchengxu** [comment]
I need a minimal vimrc and detailed environment to reproduce.

**Comment by ovidius72** [comment]
I don't know if it's the right solution but in lines 197 and 809 of "colors/space_vim_theme.vim", changing :
`if get(g: "space_vim_invert_indent_guides", 0)`
to
`if get(g:, "space_vim_invert_indent_guides", 0)` 
solved the issue for me. Notice the missing comma after `g:`

**Comment by liuchengxu** [comment]
Good catch! @ovidius72 Fixed in the master.
