### ISSUE TITLE
[Space-vim theme] There are not enough colors.

### ISSUE THREAD

**Issue by DrKyro** [liuchengxu/space-vim-theme#7]
what is wrong
`Error detected while processing /root/.vim/plugged/space-vim-theme/colors/space_vim_theme.vim:
line   11:
[Space-vim theme] There are not enough colors.`

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/space-vim-theme/blob/4790dbba31f678f75af4f4c7a1465008542bd979/colors/space_vim_theme.vim#L9-L13

This colorscheme probably won't work as expected in your environment.

**Comment by zg9uagfv01** [comment]
I just comment these code lines.
